/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NIcon: typeof import('naive-ui')['NIcon']
}
